baseURL = "http://www.shawnreviewsthings.com"
languageCode = "en-us"
title = "Shawn Reviews Things"
theme = "mediumish"
enableEmoji = true
copyright = "Shawn Rushefsky - All rights reserved"
pygmentsCodeFences = true
disqusShortname = "shawnreviewsthings"
googleAnalytics = "UA-100012560-2"

[params]
    description = "I have a lot of opinions."

[params.author]
    name = "Shawn Rushefsky"
    thumbnail = "/images/shawn-profile.jpg"
    description = "A grump old man in a grumpy young man's body."

[params.index]
  picture = "/images/shawn-profile.jpg"
  title = "Shawn Rushefsky"
  subtitle = "I have a lot of opinions."
  mdtext = '''
  I review all kinds of things: Gadgets, restuarants, hotels, open source projects, enterprise services, dogs, etc. 
  
  This site is [automatically](https://circleci.com) built from [this repo.](https://github.com/shawnrushefsky/reviews-things)
  '''
  alertbar = false

[[menu.main]]
    name = "Reviews"
    identifier = "reviews"
    weight = 199
    url = "/reviews"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 200
    url = "/blog"

[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 201
    url = "/"