version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public/site
    steps:
      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
 
      # - run:
      #     name: test our generated HTML files
      #     command: |
      #       htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
      #       --empty-alt-ignore --disable-external

      - persist_to_workspace:
          root: public
          paths:
            - site

      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy 
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run:
          name: Set up gcloud
          command: gcloud auth activate-service-account --key-file="${GCLOUD_SERVICE_KEY}"" && gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
    
      - run:
          name: Upload to Storage Bucket
          command: gsutil cp -r /tmp/workspace gs://www.shawnreviewsthings.com

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master